name: Testing Azure deployments

on:
  push:
    branches: ["master"]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the image and push it to ACR
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/emportal/api:${{ github.sha }}
        context: PortalApi

    # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        # scope: subscription
        # region: uksouth
        resourceGroupName: ${{ secrets.AZURE_RG }}
        parameters: ./deploy/staging-parameters.json gitHash=${{ github.sha }}
        template: ./deploy/main.bicep
        failOnStdErr: false