name: Trigger auto deployment for weatherforecast-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/weatherforecast-api-AutoDeployTrigger-aa4b1692-1ba1-4d77-99d2-ad74335427e7.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEATHERFORECASTAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ca535b73aad5acr.azurecr.io
          registryUsername: ${{ secrets.WEATHERFORECASTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEATHERFORECASTAPI_REGISTRY_PASSWORD }}
          containerAppName: weatherforecast-api
          resourceGroup: rg-portal-staging
          imageToBuild: ca535b73aad5acr.azurecr.io/weatherforecast-api:${{ github.sha }}
          dockerfilePath: Dockerfile

     

